config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  get  'auth/:provider/callback', to: 'sessions#callback'
  get  '/signout', to: 'sessions#destroy'

  resources :exam_histories, only: %w(index show create edit update) do
    member do
      post 'retry'
    end
    resources :user_answers, only: %w(edit update show), param: :uuid
  end

  resources :marathon, only: %w(create) do
    resources :marathon_answers, only: %w(edit update), param: :uuid
  end
end

app/models/exam_history.rb
class ExamHistory < ApplicationRecord
  has_many :user_answers, -> { order("exam_no ASC") }
  belongs_to :user

  accepts_nested_attributes_for :user_answers

  scope :certified, -> { where(exam_type: [0, 1]).order('created_at desc') }

  enum exam_type: { silver: 0, gold: 1, marathon: 2 }

  paginates_per 6  # 1ページあたり6項目表示

  def review_later_count
    user_answers.review_later.select(:id).count
  end

  def be_scored
    score = 0
    user_answers.each do |user_answer|
      if user_answer.correct?
        user_answer.score = 2
        score += 2
      else
        user_answer.score = 0
      end
    end

    self.pending = false
    self.score   = score

    save!
  end

  def exam_master_uuids
    user_answers.map{|user_answer| user_answer.master_uuid}
  end
end

app/controllers/exam_histories_controller.rb
class ExamHistoriesController < ApplicationController
  include AjaxHelper
  include AuthAccess

  before_action :set_exam_history, only: [:edit, :update, :show, :retry]
  before_action :access_own_history, only: [:edit, :update, :show, :retry]
  before_action :stop_cheating, only: [:edit, :show]

  def index
    @exam_histories = current_user.exam_histories.certified.page(params[:page])
  end

  def show
    render layout: "exams_scored"
  end

  def retry
    new_exam_history, new_user_answers = ExamMaster.duplicate(current_user, @exam_history)

    @exam_history_id = new_exam_history.id
    @uuid = new_user_answers.first.url_uuid

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def edit
    render layout: "exams"
  end

  def update
    respond_to do |format|
      if @exam_history.be_scored
        current_user.update_best_score(@exam_history)
        flash[:info] = "今回の点数は、#{@exam_history.score}点だよ！"
        format.html { redirect_to exam_histories_path }
      else
        format.html { render :edit }
      end
    end
  end

  def create
    exam_history, user_answers = ExamMaster.build_answers(current_user, params[:exam_type])
    first_user_answer = user_answers.first

    respond_to do |format|
      format.js {
        render ajax_redirect_to(edit_exam_history_user_answer_path(
          exam_history_id: exam_history.id, uuid: first_user_answer.url_uuid))
      }
    end
  end

  private
    def set_exam_history
      @exam_history = ExamHistory.includes(user_answers: :exam_master).find_by(id: params[:id])
    end
end

app/views/exam_histories/edit.html.slim
= form_for(@exam_history) do |f|
  .table
    .table-row.header
      .table-cell.exam-no
        | #
      .table-cell.question-long
        | 問題文
      .table-cell.answered
        | 未回答
      .table-cell
        | あとで見直す

    - @exam_history.user_answers.each do |user_answers|
      = link_to edit_exam_history_user_answer_path(exam_history_id: @exam_history.id, uuid: user_answers.url_uuid), class: "no-deco table-row body" do
        .table-cell
          = user_answers.exam_no
        .table-cell
          = user_answers.question.truncate(60)
        .table-cell
          - if user_answers.answered?
            span.glyphicon.glyphicon-alert
        .table-cell
          - if user_answers.review_later
            span.glyphicon.glyphicon-flag 

  = f.submit "採点する", class: "btn btn-w-md btn-gap-v btn-default"

app/views/exam_histories/index.html.slim
.row
  .col-md-12
    ul.nav.nav-boxed.nav-justified
      li
        a.create-exam href="javascript:;" data-exam-type="gold"
          = image_tag 'ruby-gold.png', size: "60x60", class: "center-image"
          p.text-muted Goldチャレンジ
          p.text-muted
            | 最高得点：
            = current_user.best_gold_score
            | 点
      li
        a.create-exam href="javascript:;" data-exam-type="silver"
          = image_tag 'ruby-silver.png', size: "60x60", class: "center-image"
          p.text-muted Silverチャレンジ
          p.text-muted
            | 最高得点：
            = current_user.best_silver_score
            | 点
      li
        a.create-exam href="javascript:;" data-exam-type="marathon"
          = image_tag 'marathon.png', size: "60x60", class: "center-image"
          p.text-muted 学習マラソン
          p.text-muted
            | 到達問題：
            = current_user.continuous_times
            | 問

div.panel-body
  - if flash[:info].present?
    .alert.alert-info role="alert"
      = flash[:info]
  - if flash[:error].present?
    .alert.alert-danger role="alert"
      = flash[:error]

.row.text-center
  - @exam_histories.each do |exam_history|
    .col-sm-6
      .panel.mini-box
        - if exam_history.gold?
          = image_tag 'ruby-gold.png', size: "60x60"
        - elsif exam_history.silver?
          = image_tag 'ruby-silver.png', size: "60x60"
        .box-info
          span.size-h6
            | 試験日:
            = exam_history.created_at.to_s(:exam_date)
          p.size-h2.no-margin
            = exam_history.score
            span.size-h3
              | /100点
          span.text-muted
            ul.list-inline
              li
                a href="javascript:;" class="no-deco retry" data-history-id="#{exam_history.id}"
                  | もう一度やる
              li &sdot;
              - if exam_history.pending?
                li
                  = link_to "続きからやる", edit_exam_history_path(exam_history), class: "no-deco"
              - else
                li
                  = link_to "解説を見る", exam_history_path(exam_history), class: "no-deco"

.row.center-pagination
  = paginate @exam_histories

app/views/exam_histories/retry.js.slim
| location.href = Routes.edit_exam_history_user_answer_path('#{@exam_history_id}', '#{@uuid}');

app/views/exam_histories/show.html.slim
.table
  .table-row.header
    .table-cell.exam-no
      | #
    .table-cell.question-short
      | 問題文
    .table-cell
      | あなたの選択
    .table-cell
      | 点数

  - @exam_history.user_answers.each do |user_answer|
    = link_to exam_history_user_answer_path(exam_history_id: @exam_history.id, uuid: user_answer.url_uuid), class: "no-deco table-row body" do
      .table-cell
        = user_answer.exam_no
      .table-cell
        = user_answer.question.truncate(25)
      .table-cell
        = user_answer.answer_id_indexes.join(",")
      .table-cell
        = user_answer.score