config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  get  'auth/:provider/callback', to: 'sessions#callback'
  get  '/signout', to: 'sessions#destroy'

  resources :exam_histories, only: %w(index show create edit update) do
    member do
      post 'retry'
    end
    resources :user_answers, only: %w(edit update show), param: :uuid
  end

  resources :marathon, only: %w(create) do
    resources :marathon_answers, only: %w(edit update), param: :uuid
  end
end

app/views/layouts/_copyright.html.slim
p.copyright.text-muted.small
  | Copyright &copy; LibertyFish Co., Ltd. 2017-
  = Date.today.year
  | . All Rights Reserved
p.text-muted.small
  | Icons made by
  a href="http://www.freepik.com" title="Freepik"  Freepik
  '
  = "from "
  a href="https://www.flaticon.com/" title="Flaticon"  www.flaticon.com
  '
  = "is licensed by "
  a href="http://creativecommons.org/licenses/by/3.0/" target="_blank" title=("Creative Commons BY 3.0")  CC 3.0 BY

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=0.5,user-scalable=yes,initial-scale=1.0"
    title
      | REx - Ruby Examination
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = favicon_link_tag
  body
    .container
      .row
        .col-lg-4.col-md-4
          section.panel.panel-box
            .panel-top.bg-danger
              .divider.divider-xl
              .divider.divider-lg
            .panel-img
              = image_tag current_user.image, class: 'img-circle'
            .list-justified-container
              ul.list-justified.text-center
                li
                  p.size-h2
                    = current_user.name
        .col-lg-8.col-md-8
          = yield
    footer
      .container
        .row
          .col-lg-12
            ul.list-inline
              li
                a href="https://www.libertyfish.co.jp/"  About
              li.footer-menu-divider &sdot;
              li
                = link_to "Sign out", signout_path
            = render 'layouts/copyright'

app/views/layouts/exams.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=0.5,user-scalable=yes,initial-scale=1.0"
    title
      | REx - Ruby Examination
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag
  body
    .container
      .row
        .col-lg-4.col-md-4
          .panel.mini-box.row
            .col-sm-3.col-xs-2
            .col-md-12.col-sm-2.col-xs-3
              - if @exam_history.gold?
                = image_tag 'ruby-gold.png', class: ["center-image", "gem-image"]
              - else
                = image_tag 'ruby-silver.png', class: ["center-image", "gem-image"]
            .col-md-12.col-sm-4.col-xs-5.text-center.box-info
              p.size-h4
                | あなたの得点
              span.size-large
                | -
                span.size-h2
                  | /100点
              p.size-h4
                | あとで見直す：
                = @exam_history.review_later_count
                | 問
            .col-sm-3.col-xs-2
          = link_to exam_histories_path, class: "no-deco"
            .panel.link-box.text-center.size-h4
              | 中断する
        .col-lg-8.col-md-8
          = yield
    footer
      .container
        .row
          .col-lg-12
            ul.list-inline
              li
                a href="https://www.libertyfish.co.jp/"  About
              li.footer-menu-divider &sdot;
              li
                = link_to "Sign out", signout_path
            = render 'layouts/copyright'

app/views/layouts/exams_scored.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=0.5,user-scalable=yes,initial-scale=1.0"
    title
      | REx - Ruby Examination
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag
  body
    .container
      .row
        .col-lg-4.col-md-4
          .panel.mini-box.row
            .col-sm-3.col-xs-2
            .col-md-12.col-sm-2.col-xs-3
              - if @exam_history.gold?
                = image_tag 'ruby-gold.png', class: ["center-image", "gem-image"]
              - else
                = image_tag 'ruby-silver.png', class: ["center-image", "gem-image"]
            .col-md-12.col-sm-4.col-xs-5.text-center.box-info
              p.size-h4
                | あなたの得点
              span.size-large
                = @exam_history.score
                span.size-h2
                  | /100点
              p.size-h4
                | あとで見直す：
                = @exam_history.review_later_count
                | 問
            .col-sm-3.col-xs-2
          = link_to exam_histories_path, class: "no-deco"
            .panel.link-box.text-center.size-h4
              | トップに戻る
        .col-lg-8.col-md-8
          = yield
    footer
      .container
        .row
          .col-lg-12
            ul.list-inline
              li
                a href="https://www.libertyfish.co.jp/"  About
              li.footer-menu-divider &sdot;
              li
                = link_to "Sign out", signout_path
            = render 'layouts/copyright'

app/views/layouts/landing.html.slim
doctype html
html lang="ja"
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"
    meta content="" name="description"
    meta content="" name="author"
    meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=0.5,user-scalable=yes,initial-scale=1.0"
    title REx - Ruby Examination
    = stylesheet_link_tag 'landing', media: 'all', 'data-turbolinks-track': 'reload'
    link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"
    = favicon_link_tag
  body
    nav.navbar.navbar-default.navbar-fixed-top.topnav role="navigation"
      .container.topnav
        .navbar-header
          span.navbar-brand.topnav REx - Ruby Examination
    .intro-header
      .container
        .row
          .col-lg-12
            .intro-message
              h1
                span.ruby-font R
                | uby
                span.ruby-font Ex
                | amination
              h3 さぁ、はじめよう
              hr.intro-divider
              ul.list-inline.intro-social-buttons
                li
                  = form_tag '/auth/github'
                    = button_tag class: 'btn btn-default btn-lg', type: "submit" do
                      i.fa.fa-github.fa-fw
                      span Join with your GitHub account
    .content-section
      .container
        = yield
    footer
      .container
        .row
          .col-lg-12
            = render 'layouts/copyright'

app/views/layouts/marathon_answers.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=0.5,user-scalable=yes,initial-scale=1.0"
    title
      | REx - Ruby Examination
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag
  body
    .container
      .row
        .col-lg-4.col-md-4
          .panel.mini-box.row
            .col-sm-3.col-xs-2
            .col-md-12.col-sm-2.col-xs-3
              = image_tag 'marathon.png', class: ["center-image", "marathon-image"]
            .col-md-12.col-sm-4.col-xs-5.text-center.box-info
              span.size-large
                span.size-h2
                  | 第
                = @user_answer.exam_no
                span.size-h2
                  | 問
              p.size-h4
                | までクリア
            .col-sm-3.col-xs-2
        .col-lg-8.col-md-8
          = yield
    footer
      .container
        .row
          .col-lg-12
            ul.list-inline
              li
                a href="https://www.libertyfish.co.jp/"  About
              li.footer-menu-divider &sdot;
              li
                = link_to "Sign out", signout_path
            = render 'layouts/copyright'

app/views/layouts/user_answers.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=0.5,user-scalable=yes,initial-scale=1.0"
    title
      | REx - Ruby Examination
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag
  body
    .container
      .row
        .col-lg-4.col-md-4
          .panel.mini-box.row
            .col-sm-3.col-xs-2
            .col-md-12.col-sm-2.col-xs-3
              - if @exam_history.gold?
                = image_tag 'ruby-gold.png', class: ["center-image", "gem-image"]
              - else
                = image_tag 'ruby-silver.png', class: ["center-image", "gem-image"]
            .col-md-12.col-sm-4.col-xs-5.text-center.box-info
              span.size-large
                = @user_answer.exam_no
                span.size-h2
                  | /50問
              p.size-h4
                | あとで見直す：
                = @exam_history.review_later_count
                | 問
            .col-sm-3.col-xs-2
          = link_to edit_exam_history_path(@exam_history), class: "no-deco"
            .panel.link-box.text-center.size-h4
              | 問題一覧
        .col-lg-8.col-md-8
          = yield
    footer
      .container
        .row
          .col-lg-12
            ul.list-inline
              li
                a href="https://www.libertyfish.co.jp/"  About
              li.footer-menu-divider &sdot;
              li
                = link_to "Sign out", signout_path
            = render 'layouts/copyright'

app/views/layouts/user_answers_scored.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=0.5,user-scalable=yes,initial-scale=1.0"
    title
      | REx - Ruby Examination
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag
  body
    .container
      .row
        .col-lg-4.col-md-4
          .panel.mini-box.row
            .col-sm-3.col-xs-2
            .col-md-12.col-sm-2.col-xs-3
              - if @exam_history.gold?
                = image_tag 'ruby-gold.png', class: ["center-image", "gem-image"]
              - else
                = image_tag 'ruby-silver.png', class: ["center-image", "gem-image"]
            .col-md-12.col-sm-4.col-xs-5.text-center.box-info
              span.size-large
                = @user_answer.exam_no
                span.size-h2
                  | /50問
              p.size-h3
                - if @user_answer.correct?
                  = content_tag(:span, class: "user-answer-ok")
                    | 正解
                - else
                  = content_tag(:span, class: "user-answer-ng")
                    | 不正解
            .col-sm-3.col-xs-2
          = link_to exam_history_path(@exam_history), class: "no-deco"
            .panel.link-box.text-center.size-h4
              | 問題一覧
        .col-lg-8.col-md-8
          = yield
    footer
      .container
        .row
          .col-lg-12
            ul.list-inline
              li
                a href="https://www.libertyfish.co.jp/"  About
              li.footer-menu-divider &sdot;
              li
                = link_to "Sign out", signout_path
            = render 'layouts/copyright'